[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gridcast"
version = "0.0.1"
description = "Short-term electricity load forecasting for PJM zones."
authors = [
  { name = "Angie Ohaeri" },
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.12"
dependencies = [
    "loguru",
    "mlflow",
    "numpy",
    "pandas",
    "python-dotenv",
    "openmeteo_requests",
    "requests_cache",
    "retry_requests",
    "scikit-learn",
    "lightgbm",
    "tqdm",
    "typer",
    "dvc[ssh]",
    "gridstatus>=0.36.0",
    "confluent-kafka",
    "prefect",
    "psycopg2-binary>=2.9.12",
    "dbt-core",
    "dbt-postgres",
    "holidays",
    "plotly>=6.9.0",
    "fastapi>=0.140.7",
    "uvicorn>=0.51.0",
    "shiny",
    "pydeck",
    "geopandas>=1.1.4",
    "shapely>=2.1.2",
    "cachetools",
]

[project.optional-dependencies]
dev = [
    "ipython",
    "jupyterlab",
    "notebook",
    "ipykernel",
    "pre-commit",
    "pytest",
    "ruff",
]

[tool.ruff]
line-length = 99
src = ["gridcast", "src"]
include = ["pyproject.toml", "gridcast/**/*.py", "src/**/*.py"]
exclude = ["_archive"]
force-exclude = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["gridcast"]
force-sort-within-sections = true

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
]
